name: 'Configure Env'
description: 'Configures Environment Properly'
inputs:
  token:
    description: 'Github token'
    required: true
  user:
    description: 'User for connecting to Github API'
    required: false
    default: kip-automation

runs:
  using: 'docker'
  image: 'Dockerfile'
