name: 'Configure Env'
description: 'Configures Environment Properly'
inputs:
  github_context:
    description: 'The context of the workflow run'
    required: true
  token:
    description: 'The github token'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_context }}

