name: 'Configure Env'
description: 'Configures Environment Properly'
inputs:
  github_context:
    description: 'The context of the workflow run'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
