name: Say Hello

on:
  push:
    branches:
      - main

jobs:
  hello:
    name: Hello
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello to Me
        uses: ../../actions
        with:
          who-to-greet: "JUSTIN"

