name: TestingTesting

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened]
    branches:
      - main
  push:
    branches:
      - "*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Testing
      uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

